version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/app/ml/models
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - algae-network

networks:
  algae-network:
    driver: bridge 